version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ctrllicenca
      POSTGRES_PASSWORD: ctrllicenca
      POSTGRES_DB: ctrllicenca
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 8081
      DATABASE_URL: postgres://ctrllicenca:ctrllicenca@db:5432/ctrllicenca?sslmode=disable
      ADMIN_EMAIL: admin@ctrllicenca.local
      ADMIN_SENHA: admin123
    ports:
      - "8081:8081"
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static

volumes:
  pgdata:
